spring:
  profiles:
    active: a
  data:
    mongodb:
      host: 47.100.39.201
      port: 27017
      database: gowithu
      username: root
      password: Superzhouqi/15
      authentication-database: gowithu
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
